import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "@/utils/trpc";

const Me: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Me Page</p>
    </>
  );
};

export default Me;
